<a href="https://colab.research.google.com/github/DeuklyoungKo/toStartDeepLearningWithPyTorch/blob/main/chap03_01_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [78]:
torch.manual_seed(1)

In [79]:
x_train = torch.FloatTensor([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
y_train = torch.FloatTensor([[6],[9],[11],[13],[15],[17],[19],[21],[23]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])
tensor([[ 6.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.],
        [23.]])
torch.Size([9, 1])


In [80]:
#기중치 초기화
W = torch.zeros(1, requires_grad=True)
print(W)
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [81]:
hypothesis = x_train*W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [82]:
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(250.2222, grad_fn=<MeanBackward0>)


##경사 하강법 구현하기

In [83]:
optimizer = optim.SGD([W,b], lr=0.01)

In [84]:
nb_epochs = 100

for epoch in range(nb_epochs + 1):

  hypothesis = x_train*W + b

  cost = torch.mean((hypothesis -y_train)**2)

  optimizer.zero_grad()
  print("W,b 1: ",W,b,epoch)  
  cost.backward()
  print("W,b 2: ",W,b,epoch)  
  optimizer.step()
  print("W,b 3: ",W,b,epoch)

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
    ))
  print("------------------")

W,b 1:  tensor([0.], requires_grad=True) tensor([0.], requires_grad=True) 0
W,b 2:  tensor([0.], requires_grad=True) tensor([0.], requires_grad=True) 0
W,b 3:  tensor([1.7644], requires_grad=True) tensor([0.2978], requires_grad=True) 0
Epoch    0/100 W: 1.764, b: 0.298 Cost: 250.222229
------------------
W,b 1:  tensor([1.7644], requires_grad=True) tensor([0.2978], requires_grad=True) 1
W,b 2:  tensor([1.7644], requires_grad=True) tensor([0.2978], requires_grad=True) 1
W,b 3:  tensor([2.3816], requires_grad=True) tensor([0.4132], requires_grad=True) 1
------------------
W,b 1:  tensor([2.3816], requires_grad=True) tensor([0.4132], requires_grad=True) 2
W,b 2:  tensor([2.3816], requires_grad=True) tensor([0.4132], requires_grad=True) 2
W,b 3:  tensor([2.5964], requires_grad=True) tensor([0.4645], requires_grad=True) 2
------------------
W,b 1:  tensor([2.5964], requires_grad=True) tensor([0.4645], requires_grad=True) 3
W,b 2:  tensor([2.5964], requires_grad=True) tensor([0.4645], requir